package com.colors.game.ui

import androidx.compose.runtime.compositionLocalOf
import com.colors.game.data.model.Difficulty
import com.colors.game.data.model.Language

// ──────────────────────────────────────────────────────────────────────────────
// All UI strings in one place — supports English and Spanish.
// Access via LocalStrings.current in any composable.
// ──────────────────────────────────────────────────────────────────────────────

data class AppStrings(
    // General
    val back: String,
    val settings: String,
    val mainMenu: String,
    val resume: String,
    val restart: String,

    // Main menu
    val levelsCompleted: (Int) -> String,
    val start: String,
    val nextLevel: (Int) -> String,
    val resumeLevel: (Int) -> String,
    val levels: String,
    val exit: String,

    // Settings
    val accessibility: String,
    val colorBlindMode: String,
    val colorBlindModeDesc: String,
    val audio: String,
    val sound: String,
    val soundDesc: String,
    val music: String,
    val musicDesc: String,
    val haptics: String,
    val vibration: String,
    val vibrationDesc: String,
    val languageLabel: String,
    val languageDesc: String,
    val versionInfo: String,

    // Level selector
    val selectLevel: String,
    val locked: String,
    val easy: String,
    val medium: String,
    val hard: String,

    // Game HUD
    val levelN: (Int) -> String,
    val moves: String,
    val time: String,
    val pause: String,

    // Pause dialog
    val pausedTitle: String,

    // Result dialog
    val completed: String,
    val gameOver: String,
    val noMovesLeft: String,
    val nextLevelBtn: String,
    val tryAgain: String,

    // Leaderboard
    val leaderboard: String,
    val rankingsTab: String,
    val movesTab: String,
    val timeTab: String,
    val infoTab: String,
    val rankSymbol: String,
    val signInToCompete: String,
    val signInDesc: String,
    val signInButton: String,
    val noScoresYet: String,
    val movesUnit: (Int) -> String,
    val timeUnit: (Int) -> String,
    val viewRankings: String,

    // Level detail dialog
    val bestTime: String,
    val bestMoves: String,
    val starRequirements: String,
    val movesThreshold: (Int) -> String,   // "≤ N moves" / "≤ N movimientos"
    val anyCompletion: String,             // label for 1-star row
    val notCompleted: String,
    val completedStatus: String,
    val play: String,
    val replay: String,
    val maxMovesLabel: (Int) -> String,    // "Max: N moves" / "Máx: N movimientos"

    // Premium
    val getPremium: String,
    val premiumOwned: String,
    val premiumDesc: String,
    val redeemCode: String,
    val redeemCodeTitle: String,
    val redeemCodeHint: String,
    val redeemCodeButton: String,
    val redeemCodeSuccess: String,
    val redeemCodeError: String,

    // Tutorial
    val howToPlay: String,
    val skip: String,
    val previous: String,
    val next: String,
    val letsPlay: String,
    val tutPage1Title: String,
    val tutPage1Desc: String,
    val tutPage2Title: String,
    val tutPage2Desc: String,
    val tutPage3Title: String,
    val tutPage3Desc: String,
    val tutPage4Title: String,
    val tutPage4Desc: String,
    val tutCornerLabel: String,
    val tutColorChangesTo: String,
    val tutTapColor: String,
    val tutExpandedN: (Int) -> String,
    val tutInitialGroupN: (Int) -> String,
    val tutAfterExpandDesc: String,
    val tutBeforeExpandDesc: String,
    val tutWinDesc: String,
)

fun AppStrings.difficultyName(d: Difficulty): String = when (d) {
    Difficulty.EASY   -> easy
    Difficulty.MEDIUM -> medium
    Difficulty.HARD   -> hard
}

// ── English ───────────────────────────────────────────────────────────────────

val EnglishStrings = AppStrings(
    back                = "Back",
    settings            = "Settings",
    mainMenu            = "Main Menu",
    resume              = "Resume",
    restart             = "Restart",
    levelsCompleted     = { n -> "$n / 500 levels completed" },
    start               = "Start",
    nextLevel           = { n -> "Level $n" },
    resumeLevel         = { n -> "Resume level $n" },
    levels              = "Levels",
    exit                = "Exit",
    accessibility       = "Accessibility",
    colorBlindMode      = "Color blind mode",
    colorBlindModeDesc  = "Accessible color palette",
    audio               = "Audio",
    sound               = "Sound",
    soundDesc           = "Sound effects",
    music               = "Music",
    musicDesc           = "Background music",
    haptics             = "Haptics",
    vibration           = "Vibration",
    vibrationDesc       = "Haptic feedback while playing",
    languageLabel       = "Language",
    languageDesc        = "App language",
    versionInfo         = "Color Puzzles v1.0 · 500 levels",
    selectLevel         = "Select Level",
    locked              = "Locked",
    easy                = "Easy",
    medium              = "Medium",
    hard                = "Hard",
    levelN              = { n -> "Level $n" },
    moves               = "moves",
    time                = "time",
    pause               = "Pause",
    pausedTitle         = "Paused",
    completed           = "Completed!",
    gameOver            = "Game Over!",
    noMovesLeft         = "No moves left",
    nextLevelBtn        = "Next level",
    tryAgain            = "Try again",
    leaderboard         = "Leaderboard",
    rankingsTab         = "Rankings",
    movesTab            = "Moves",
    timeTab             = "Time",
    infoTab             = "Info",
    rankSymbol          = "#",
    signInToCompete     = "Sign in to compete",
    signInDesc          = "Sign in with Google Play Games to appear on the leaderboard.",
    signInButton        = "Sign in",
    noScoresYet         = "No scores yet — be the first!",
    movesUnit           = { n -> "$n moves" },
    timeUnit            = { s -> "%02d:%02d".format(s / 60, s % 60) },
    viewRankings        = "View rankings",
    bestTime            = "Best time",
    bestMoves           = "Best moves",
    starRequirements    = "Star requirements",
    movesThreshold      = { n -> "≤ $n moves" },
    anyCompletion       = "Complete the level",
    notCompleted        = "Not completed",
    completedStatus     = "Completed",
    play                = "Play",
    replay              = "Play again",
    maxMovesLabel       = { n -> "Max: $n moves" },
    getPremium          = "Get Premium",
    premiumOwned        = "Premium",
    premiumDesc         = "No ads · One-time purchase",
    redeemCode          = "Redeem a code",
    redeemCodeTitle     = "Redeem code",
    redeemCodeHint      = "Enter your code",
    redeemCodeButton    = "Redeem",
    redeemCodeSuccess   = "✓ Code accepted — welcome to Premium!",
    redeemCodeError     = "Invalid code. Please try again.",
    howToPlay           = "How to play",
    skip                = "Skip",
    previous            = "Previous",
    next                = "Next",
    letsPlay            = "Let's play!",
    tutPage1Title       = "Corner rules",
    tutPage1Desc        = "You always start from the top-left corner. The highlighted group is yours — no need to tap any cell.",
    tutPage2Title       = "Pick a color",
    tutPage2Desc        = "Tap a color from the bottom panel. Your whole group changes to that color instantly.",
    tutPage3Title       = "Expand your territory",
    tutPage3Desc        = "Adjacent cells of the new color automatically merge with your group, making it larger.",
    tutPage4Title       = "Complete the board!",
    tutPage4Desc        = "Turn all cells to the same color using the fewest moves. Get 3 stars!",
    tutCornerLabel      = "↖ Corner group already selected",
    tutColorChangesTo   = "⬆  group changes to this color",
    tutTapColor         = "Tap a color to select it",
    tutExpandedN        = { n -> "Expanded! ($n cells)" },
    tutInitialGroupN    = { n -> "Initial group ($n cells)" },
    tutAfterExpandDesc  = "Adjacent cells merged with the group",
    tutBeforeExpandDesc = "Change to green → absorbs all adjacent green cells",
    tutWinDesc          = "Fewer moves = more stars!",
)

// ── Spanish ───────────────────────────────────────────────────────────────────

val SpanishStrings = AppStrings(
    back                = "Atrás",
    settings            = "Ajustes",
    mainMenu            = "Menú principal",
    resume              = "Reanudar",
    restart             = "Reiniciar",
    levelsCompleted     = { n -> "$n / 500 niveles completados" },
    start               = "Empezar",
    nextLevel           = { n -> "Nivel $n" },
    resumeLevel         = { n -> "Reanudar nivel $n" },
    levels              = "Niveles",
    exit                = "Salir",
    accessibility       = "Accesibilidad",
    colorBlindMode      = "Modo daltónico",
    colorBlindModeDesc  = "Paleta de colores accesible",
    audio               = "Audio",
    sound               = "Sonido",
    soundDesc           = "Efectos de sonido",
    music               = "Música",
    musicDesc           = "Música de fondo",
    haptics             = "Táctil",
    vibration           = "Vibración",
    vibrationDesc       = "Respuesta háptica al jugar",
    languageLabel       = "Idioma",
    languageDesc        = "Idioma de la aplicación",
    versionInfo         = "Color Puzzles v1.0 · 500 niveles",
    selectLevel         = "Seleccionar Nivel",
    locked              = "Bloqueado",
    easy                = "Fácil",
    medium              = "Medio",
    hard                = "Difícil",
    levelN              = { n -> "Nivel $n" },
    moves               = "movimientos",
    time                = "tiempo",
    pause               = "Pausa",
    pausedTitle         = "Pausa",
    completed           = "¡Completado!",
    gameOver            = "¡Fin del juego!",
    noMovesLeft         = "Sin movimientos",
    nextLevelBtn        = "Siguiente nivel",
    tryAgain            = "Intentar de nuevo",
    bestTime            = "Mejor tiempo",
    bestMoves           = "Mejor resultado",
    starRequirements    = "Requisitos de estrellas",
    movesThreshold      = { n -> "≤ $n movimientos" },
    anyCompletion       = "Completa el nivel",
    notCompleted        = "Sin completar",
    completedStatus     = "Completado",
    play                = "Jugar",
    replay              = "Jugar de nuevo",
    maxMovesLabel       = { n -> "Máx: $n movimientos" },
    leaderboard         = "Clasificación",
    rankingsTab         = "Rankings",
    movesTab            = "Movimientos",
    timeTab             = "Tiempo",
    infoTab             = "Info",
    rankSymbol          = "#",
    signInToCompete     = "Inicia sesión para competir",
    signInDesc          = "Inicia sesión con Google Play Games para aparecer en la clasificación.",
    signInButton        = "Iniciar sesión",
    noScoresYet         = "Sin puntuaciones aún — ¡sé el primero!",
    movesUnit           = { n -> "$n movimientos" },
    timeUnit            = { s -> "%02d:%02d".format(s / 60, s % 60) },
    viewRankings        = "Ver clasificación",
    getPremium          = "Obtener Premium",
    premiumOwned        = "Premium",
    premiumDesc         = "Sin anuncios · Pago único",
    redeemCode          = "Canjear un código",
    redeemCodeTitle     = "Canjear código",
    redeemCodeHint      = "Introduce tu código",
    redeemCodeButton    = "Canjear",
    redeemCodeSuccess   = "✓ Código aceptado — ¡bienvenido a Premium!",
    redeemCodeError     = "Código inválido. Inténtalo de nuevo.",
    howToPlay           = "Cómo jugar",
    skip                = "Saltar",
    previous            = "Anterior",
    next                = "Siguiente",
    letsPlay            = "¡A jugar!",
    tutPage1Title       = "La esquina manda",
    tutPage1Desc        = "Siempre empiezas desde la esquina superior izquierda. El grupo resaltado es tuyo — no hay que tocar ninguna celda.",
    tutPage2Title       = "Elige un color",
    tutPage2Desc        = "Pulsa un color del panel inferior. Todo tu grupo cambiará a ese color al instante.",
    tutPage3Title       = "Expande tu territorio",
    tutPage3Desc        = "Las celdas adyacentes del nuevo color se fusionan automáticamente con tu grupo, haciéndolo más grande.",
    tutPage4Title       = "¡Completa el tablero!",
    tutPage4Desc        = "Convierte todas las celdas al mismo color usando el mínimo de movimientos. ¡Consigue 3 estrellas!",
    tutCornerLabel      = "↖ El grupo de la esquina ya está seleccionado",
    tutColorChangesTo   = "⬆  el grupo cambia a este color",
    tutTapColor         = "Toca un color para seleccionarlo",
    tutExpandedN        = { n -> "¡Expandido! ($n celdas)" },
    tutInitialGroupN    = { n -> "Grupo inicial ($n celdas)" },
    tutAfterExpandDesc  = "Las verdes adyacentes se fusionan con el grupo",
    tutBeforeExpandDesc = "Cambia a verde → absorbe todas las celdas verdes contiguas",
    tutWinDesc          = "¡Cuantos menos movimientos, más estrellas!",
)

// ── Provider ──────────────────────────────────────────────────────────────────

fun stringsFor(language: Language): AppStrings = when (language) {
    Language.EN -> EnglishStrings
    Language.ES -> SpanishStrings
}

val LocalStrings = compositionLocalOf { EnglishStrings }
